config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :bigint           not null, primary key
#  image      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_photos_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Photo < ApplicationRecord
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  mount_uploader :image, ImageUploader

  validates :image, presence: true

  def save_with_tags(tag_names)
    valid = true
    ActiveRecord::Base.transaction do
      self.tags = tag_names.split(',').uniq.map { |name| Tag.find_or_initialize_by(name: name.strip) }
      valid &= save
      raise ActiveRecord::Rollback unless valid
    end
    valid
  end
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_tags_on_name  (name) UNIQUE
#
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :photos, through: :taggings

  validates :name, presence: true, uniqueness: true

  def self.all_names
    order(:name).to_json(only: :name)
  end
end

app/models/tagging.rb
# == Schema Information
#
# Table name: taggings
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  photo_id   :bigint           not null
#  tag_id     :bigint           not null
#
# Indexes
#
#  index_taggings_on_photo_id             (photo_id)
#  index_taggings_on_photo_id_and_tag_id  (photo_id,tag_id) UNIQUE
#  index_taggings_on_tag_id               (tag_id)
#
# Foreign Keys
#
#  fk_rails_...  (photo_id => photos.id)
#  fk_rails_...  (tag_id => tags.id)
#
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :photo

  validates :tag_id, uniqueness: { scope: :photo_id }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                            :bigint           not null, primary key
#  avatar                        :string
#  crypted_password              :string
#  email                         :string           not null
#  name                          :string           not null
#  new_post_notification_allowed :boolean          default(TRUE), not null
#  role                          :integer          default("general"), not null
#  salt                          :string
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :photos, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  enum role: { general: 0, admin: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :require_login
  add_flash_types :info, :success, :warning

  private

  def not_authenticated
    redirect_to login_path, warning: t('information.require_login')
  end

  def no_login_required
    redirect_to photos_path if logged_in?
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  skip_before_action :require_login, only: %i[index show]

  def index
    @pagy, @photos = pagy(Photo.all)
  end

  def show; end

  def new
    @photo = Photo.new
    @all_tags = Tag.all_names
  end

  def create
    @photo = current_user.photos.build(photo_params)
    @tag_names = params.dig(:photo, :tag_names)
    if @photo.save_with_tags(@tag_names)
      redirect_to photos_path, success: t('.success')
    else
      @all_tags = Tag.all_names
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  private

  def photo_params
    params.require(:photo).permit(:image, :image_cache)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login

  def top
    redirect_to photos_path if logged_in?
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  before_action :no_login_required, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = login(user_params[:email], user_params[:password])

    if @user
      redirect_back_or_to photos_path, success: t('.success')
    else
      @user = User.new(user_params)
      @error_message = t('user_sessions.create.error_message')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, success: t('.success')
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  before_action :no_login_required, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def page_title(page_title = '')
    base_title = t('defaults.title')

    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end

  def current_page_icon(path)
    current_page?(path) ? 'text-accent' : ''
  end
end

app/views/layouts/application.html.slim
doctype html
html#awesome-stuff-here
  head
    title
      = page_title(yield(:title))
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    meta[name="turbo-cache-control" content="no-preview"]
    script[src="https://cdn.jsdelivr.net/npm/@yaireo/tagify"]
    script[src="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.polyfills.min.js"]
    link[href="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css"]
    link[href="https://use.fontawesome.com/releases/v6.2.0/css/all.css" rel="stylesheet"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true
  body
    - if logged_in?
      = render 'shared/after_login_header'
      = render 'shared/after_login_navbar'
    - else
      = render 'shared/before_login_header'
      = render 'shared/before_login_navbar'
    = render 'shared/flash_message'
    = yield

app/views/photos/_form.html.slim
= form_with model: photo, class: 'w-full px-8 md:max-w-2xl', data: { controller: 'image' } do |f|
  - if f.object.errors.present?
    .grid.place-items-center
      p.text-error.text-sm.mb-5
        i.fas.fa-triangle-exclamation.mr-1
        = f.object.errors.full_messages.first
  .form-control
    label.label
      span.label-text
        span.text-lg.required
          = f.label :image
        span.text-xs
          = t('information.max_file_size')
    = f.file_field :image, class: 'file-input file-input-bordered file-input-info w-full max-w-xs', data: { image_target: 'select', action: 'change->image#imagePreview' }, accept: 'image/jpg,image/jpeg,image/gif,image/png'
    = f.hidden_field :image_cache
  .mt-5.mb-3
    - if photo.image?
      = image_tag photo.image.url, data: { image_target: 'preview'  }
    - else
      = image_tag '', data: { image_target: 'preview'  }
  .form-control data-controller='tag'
    label.label
      span.label-text
        span.text-lg
          = f.label :tag_names
        span.text-xs
          = t('information.tagging')
    = f.text_field :tag_input, class: 'input input-info items-center px-2 py-1 custom-tagify', data: { tag_target:'tag_input' }
    = f.hidden_field :tag_names, value: tag_names, data: { tag_target:'tag_names'}
    . value=all_tags data-tag-target='all_tags'
  .mt-7.mb-20
    = f.submit submit_text, class: 'btn btn-primary btn-block text-white', disabled: true, data: { image_target: 'submit', turbo: false }

app/views/photos/_photo.html.slim
.w-full.mb-5.md:px-2.md:my-2 id='photo-id-#{photo.id}'
  = link_to image_tag(photo.image_url, class: 'w-full sm:rounded-lg md:w-96 md:h-96 md:object-cover'), photo_path(photo)

app/views/photos/edit.html.slim
h1 Photos#edit
p Find me in app/views/photos/edit.html.slim

app/views/photos/index.html.slim
- content_for(:title, t('.title'))
- if @photos.present?
  .container.max-w-full.mx-0.mb-14
    .grid.place-items-center.mx-auto.pt-10.sm:px-10
      #photos.grid.place-items-center.md:grid-cols-2.lg:grid-cols-3.2xl:grid-cols-4
      = turbo_frame_tag :load_more, loading: :lazy, src: photos_path(format: :turbo_stream)
- else
  .container.mx-auto
    .grid.place-items-center
      .grid.place-items-center.mt-20
        p.text-lg = t('.no_posts')
        p.my-8 = t(".why_don't_you_post?")
        - if logged_in?
          .w-full
            = link_to t('.to_new_photo_page'), new_photo_path, class: 'btn btn-primary btn-block btn-wide text-white'
        - else
          .w-full
            = link_to t('.to_login_page'), login_path, class: 'btn btn-primary btn-block btn-wide text-white'
          .divider.my-5.text-gray-400 OR
          .w-full.mb-10
            = link_to t('action.create_account'), signup_path, class: 'btn btn-primary btn-wide text-white'

app/views/photos/index.turbo_stream.slim
= turbo_stream.append :photos do
  = render @photos

- if @pagy.next.present?
  = turbo_stream.replace :load_more do
    = turbo_frame_tag :load_more, loading: :lazy, src: photos_path(page: @pagy.next, format: :turbo_stream)

app/views/photos/new.html.slim
- content_for(:title, t('.title'))
.container.mx-auto
  .grid.place-items-center
    h1.text-2xl.pt-10.pb-5
      = t('.title')
  .grid.place-items-center
    = render partial: 'form', locals: { photo: @photo, tag_names: @tag_names, all_tags: @all_tags, submit_text: t('.post') }

app/views/photos/show.html.slim
h1 Photos#show
p Find me in app/views/photos/show.html.slim

app/views/shared/_after_login_header.html.slim
- if current_page?(photos_path)
  header.transition-all.duration-300.ease--in-out.z-20.flex.items-center.w-full.h-12.sm:h-14.bg-base-200 data-controller='header' data-header-target='header'
    = render 'shared/after_login_header_contents'
- else
  header.flex.items-center.w-full.h-12.sm:h-14.bg-base-200
    = render 'shared/after_login_header_contents'

app/views/shared/_after_login_header_contents.html.slim
.flex-1.px-4.sm:px-7.text-accent.text-xl.font-title
  - if current_page?(photos_path)
    a class="#{current_page_icon(photos_path)}" href='#awesome-stuff-here' data-controller='scroll-to'
      = t('defaults.title')
  - else
    = link_to t('defaults.title'), photos_path
.flex.justify-end.items-center.text-icon
  = link_to '#' do
    .text-lg.sm:text-xl.pr-7
      i.fas.fa-magnifying-glass
  = link_to '#' do
    .text-lg.sm:text-xl.pr-7
      i.fas.fa-map-location-dot
  - if current_page?(photos_path)
    a class="hidden sm:flex #{current_page_icon(photos_path)}" href='#awesome-stuff-here' data-controller='scroll-to'
      .text-lg.sm:text-xl.pr-7
        i.fas.fa-image
  - else
    = link_to photos_path, class: "hidden sm:flex #{current_page_icon(photos_path)}" do
      .text-lg.sm:text-xl.pr-7
        i.fas.fa-image
  = link_to new_photo_path, class: "hidden sm:flex #{current_page_icon(new_photo_path)}" do
    .text-lg.sm:text-xl.pr-7
      i.fas.fa-plus
  = link_to '#' do
    .text-lg.sm:text-xl.pr-5
      i.fas.fa-bell
  #menu.z-10.pr-6.sm:pr-8 data-controller='menu' data-menu-target='menu'
    .menu-btn.btn.btn-ghost.btn-square.btn-sm data-action='click->menu#clickMenuBtn click@document->menu#clickDocument'
    ul.menu-content.hidden.menu.shadow.bg-base-100.rounded-bl-lg.w-52.sm:w-60.mt-2.5.sm:mt-3.5.pt-4.pb-8.text-accent data-menu-target='content'
      li
        = link_to '#', class: 'px-8 sm:w-60 hidden sm:flex' do
            i.fas.fa-lightbulb.text-lg.sm:px-1
            = t('defaults.interested')
      li
        = link_to '#', class: 'px-8 sm:w-60 hidden sm:flex' do
            i.fas.fa-images.text-lg
            = t('defaults.album')
      li
        = link_to '#', class: 'px-8 sm:w-60 hidden sm:flex' do
            i.fas.fa-user.text-lg class='sm:pl-0.5 sm:pr-0.5'
            = t('defaults.my_page')
      li
        = link_to '#', class: 'px-8 w-52 sm:w-60' do
            i.fas.fa-gear.text-lg class='sm:pl-0.5'
            = t('defaults.account_settings')
      li
        = link_to logout_path, class: 'px-8 w-52 sm:w-60', data: { turbo_method: :delete } do
            i.fas.fa-right-from-bracket.text-lg class='sm:pl-0.5'
            = t('defaults.logout')
      .divider.w-full.my-1
      li  = link_to t('static_pages.tos'), '#', class: 'text-sm px-8 py-2 w-52 sm:w-60'
      li  = link_to t('static_pages.privacy_policy'), '#', class: 'text-sm px-8 py-2 w-52 sm:w-60'
      li  = link_to t('static_pages.contact'), '#', class: 'text-sm mb-4 px-8 py-2 w-52 sm:w-60'
      p.text-xxs.text-icon.px-8 = t('defaults.copyright')

app/views/shared/_after_login_navbar.html.slim
.btm-nav.btm-nav-sm.bg-base-200.z-10.text-xl.text-icon.sm:hidden
  - if current_page?(photos_path)
    a class="flex #{current_page_icon(photos_path)}" href='#awesome-stuff-here' data-controller='scroll-to'
      .fas.fa-image
      p.text-xxs.font-bold = t('defaults.photos')
  - else
    = link_to photos_path, class: current_page_icon(photos_path) do
        i.fas.fa-image
        p.text-xxs.font-bold = t('defaults.photos')
  = link_to '#' do
    i.fas.fa-lightbulb
    p.text-xxs.font-bold = t('defaults.interested')
  = link_to new_photo_path, class: current_page_icon(new_photo_path) do
    i.fas.fa-plus
    p.text-xxs.font-bold = t('defaults.new_post')
  = link_to '#' do
    i.fas.fa-images
    p.text-xxs.font-bold = t('defaults.album')
  = link_to '#' do
    i.fas.fa-user
    p.text-xxs.font-bold = t('defaults.my_page')

app/views/shared/_before_login_header.html.slim
- if current_page?(photos_path)
  header.transition-all.duration-300.ease--in-out.z-20.flex.items-center.w-full.h-12.sm:h-14.bg-base-200 data-controller='header' data-header-target='header'
    = render 'shared/before_login_header_contents'
- else
  header.flex.items-center.w-full.h-12.sm:h-14.bg-base-200
    = render 'shared/before_login_header_contents'

app/views/shared/_before_login_header_contents.html.slim
.flex-1.px-4.sm:px-7.text-accent.text-xl.font-title
  = link_to t('defaults.title'), root_path
.flex.justify-end.items-center.gap-7.text-icon
  = link_to '#' do
    .text-lg.sm:text-xl
      i.fas.fa-magnifying-glass
  = link_to '#' do
    .text-lg.sm:text-xl
      i.fas.fa-map-location-dot
  - if current_page?(photos_path)
    a class="hidden sm:flex #{current_page_icon(photos_path)}" href='#awesome-stuff-here' data-controller='scroll-to'
      .inline-block.text-center.text-lg.sm:text-xl
        i.fas.fa-image
        p.text-xxs.font-bold = t('defaults.photos')
  - else
    = link_to photos_path, class: "hidden sm:flex #{current_page_icon(photos_path)}" do
      .inline-block.text-center.text-lg.sm:text-xl
        i.fas.fa-image
        p.text-xxs.font-bold = t('defaults.photos')
  = link_to login_path, class: "hidden sm:flex #{current_page_icon(login_path)}" do
    .inline-block.text-center.text-lg.sm:text-xl
      i.fas.fa-right-to-bracket
      p.text-xxs.font-bold = t('defaults.login')
  = link_to signup_path, class: "hidden sm:flex #{current_page_icon(signup_path)}" do
    .inline-block.text-center.text-lg.sm:text-xl
      i.fas.fa-user-plus
      p.text-xxs.font-bold = t('defaults.signup')
  #menu.z-10.pr-6.sm:pr-8 data-controller='menu' data-menu-target='menu'
    .menu-btn.btn.btn-ghost.btn-square.btn-sm data-action='click->menu#clickMenuBtn click@document->menu#clickDocument'
    ul.menu-content.hidden.menu.shadow.bg-base-100.rounded-bl-lg.w-52.sm:w-60.mt-2.5.sm:mt-3.5.pt-4.pb-8.text-accent data-menu-target='content'
      li  = link_to t('static_pages.tos'), '#', class: 'text-sm px-8 py-2 w-52 sm:w-60'
      li  = link_to t('static_pages.privacy_policy'), '#', class: 'text-sm px-8 py-2 w-52 sm:w-60'
      li  = link_to t('static_pages.contact'), '#', class: 'text-sm mb-4 px-8 py-2 w-52 sm:w-60'
      p.text-xxs.text-icon.px-8 = t('defaults.copyright')

app/views/shared/_before_login_navbar.html.slim
.btm-nav.btm-nav-sm.bg-base-200.z-10.text-xl.text-icon.sm:hidden
  - if current_page?(photos_path)
    a class="flex #{current_page_icon(photos_path)}" href='#awesome-stuff-here' data-controller='scroll-to'
      .fas.fa-image
      p.text-xxs.font-bold = t('defaults.photos')
  - else
    = link_to photos_path, class: current_page_icon(photos_path) do
      i.fas.fa-image
      p.text-xxs.font-bold = t('defaults.photos')
  = link_to login_path, class: current_page_icon(login_path) do
    i.fas.fa-right-to-bracket
    p.text-xxs.font-bold = t('defaults.login')
  = link_to signup_path, class: current_page_icon(signup_path) do
    i.fas.fa-user-plus
    p.text-xxs.font-bold = t('defaults.signup')

app/views/shared/_error_messages.html.slim
- if object.errors.present?
  - object.errors.full_messages.each do |message|
    .grid.place-items-center
      p.text-error.text-sm.mb-2
        i.fas.fa-triangle-exclamation.mr-1
        = message

app/views/shared/_flash_message.html.slim
div[data-controller='notification'
    class='transition transform duration-1000 hidden toast z-30 mb-9 sm:toast-top sm:mt-12'
    data-notification-delay-value='4000'
    data-transition-enter-from='opacity-0 translate-x-3'
    data-transition-enter-to='opacity-100 translate-x-0'
    data-transition-leave-from='opacity-100 translate-x-0'
    data-transition-leave-to='opacity-0 translate-x-3']
  - if success
    .alert.alert-success.shadow-lg
      .flex.w-full
        .flex-1
          i.far.fa-circle-check.mr-2
          = success
        .flex.justify-end
          button data-action='notification#hide'
            i.fas.fa-xmark
  - if warning
    .alert.alert-warning.shadow-lg
      .flex.w-full
        .flex-1
          i.fas.fa-triangle-exclamation.mr-2
          = warning
        .flex.justify-end
          button data-action='notification#hide'
            i.fas.fa-xmark

app/views/shared/_password_visibility.html.slim
button.indicator-item.indicator-middle.pb-5.mr-6.md:mr-7.text-sm.text-slate-500 type='button' data-action='password-visibility#toggle'
  span data-password-visibility-target='icon'
    i.far.fa-eye-slash
  span.hidden data-password-visibility-target='icon'
    i.far.fa-eye

app/views/static_pages/top.html.slim
.hero.min-h-full
  .hero-content.text-center
    .w-full.px-8.md:max-w-2xl
      h1.text-4xl.font-bold.text-primary トップページ
      p.my-10 サービス概要や使い方の説明が入ります。
      .my-5
        = link_to t('.to_photos'), photos_path, class: 'btn btn-primary btn-wide btn-outline'
      .my-5
        = link_to t('action.create_account'), signup_path, class: 'btn btn-primary btn-wide text-white'

app/views/user_sessions/new.html.slim
- content_for(:title, t('.title'))
.container.mx-auto.mb-10
  .grid.place-items-center
    h1.text-2xl.pt-10.pb-5
      = t('.title')
    - if @error_message.present?
      p.text-error.text-sm.mb-5
        i.fas.fa-triangle-exclamation.mr-1
        = @error_message
  .grid.place-items-center
    = form_with model: @user, url: login_path, method: :post, class: 'w-full px-8 sm:max-w-xl', data: { controller: 'login' } do |f|
      .form-control.mb-2
        label.label
          span.label-text.text-base
            = f.label :email, User.human_attribute_name(:email)
        = f.text_field :email, class: 'input input-info', autocomplete: 'email', data: { login_target: 'email' }
      .form-control.mb-2
        label.label
          span.label-text.text-base
            = f.label :password,  User.human_attribute_name(:password)
        .w-full.indicator.input-success  data-controller='password-visibility'
          = f.password_field :password, class: 'input input-info flex-1', data: { password_visibility_target: 'input', login_target: 'password' }, spellcheck: 'false'
          = render 'shared/password_visibility'
      .mt-7.mb-2
        = f.submit t('defaults.login'), class: 'btn btn-primary btn-block text-white', disabled: true, data: { login_target: 'submit', turbo: false }
    .grid.place-items-center
      .mt-5
        = link_to t('.password_forget'), '#', class: 'link text-blue-500 text-sm'
  .grid.place-items-center
    p.mt-7.px-8.text-xs
      = link_to t('static_pages.tos'), '#', class: 'link text-blue-500'
      = t('information.and')
      = link_to t('static_pages.privacy_policy'), '#', class: 'link text-blue-500'
      = t('information.consent')
    .divider.w-full.px-8.py-3.md:max-w-2xl
  .grid.place-items-center
    p  = t(".don't_have_an_account")
    .mt-3.mb-10
      = link_to t('.to_register_page'), signup_path, class: 'btn btn-primary btn-outline btn-wide'

app/views/users/new.html.slim
- content_for(:title, t('.title'))
.container.mx-auto.mb-10
  .grid.place-items-center
    h1.text-2xl.pt-10.pb-5
      = t('.title')
  .grid.place-items-center
    = form_with model: @user, url: signup_path, class: 'w-full px-8 sm:max-w-xl', data: { controller: 'signup' } do |f|
      = render 'shared/error_messages', object: f.object
      .form-control.my-2
        label.label
          span.label-text.text-base.required
            = f.label :name
          span.label-text.required-before.text-xs.mb-5
            = t('information.required')
        = f.text_field :name, placeholder: t('.name_placeholder'), class: 'input input-info', autocomplete: 'name', data: { signup_target: 'name' }
        p data-signup-target='error_name'
      .form-control.mb-2
        label.label
          span.label-text.text-base.required
            = f.label :email
        = f.text_field :email, placeholder: t('.email_placeholder'), class: 'input input-info', autocomplete: 'email', data: { signup_target: 'email' }
        p data-signup-target='error_email'
      .form-control.mb-2
        label.label
          span.label-text.text-base.required
            = f.label :password
        .w-full.indicator.input-success  data-controller='password-visibility'
          = f.password_field :password, placeholder: t('.password_placeholder'), class: 'input input-info w-full', autocomplete: 'new-password', data: { password_visibility_target: 'input', signup_target: 'password' }, spellcheck: 'false'
          = render 'shared/password_visibility'
        p data-signup-target='error_password'
      .form-control
        label.label
          span.label-text.text-base.required
            = f.label :password_confirmation
        .w-full.indicator.input-success  data-controller='password-visibility'
          = f.password_field :password_confirmation, placeholder: t('.confirmation_placeholder'), class: 'input input-info w-full', autocomplete: 'new-password', data: { password_visibility_target: 'input', signup_target: 'password_confirmation' }, spellcheck: 'false'
          = render 'shared/password_visibility'
        p data-signup-target='error_password_confirmation'
      .mt-7
        = f.submit t('.register'), class: 'btn btn-primary btn-block text-white', disabled: true, data: { signup_target: 'submit' }
  .grid.place-items-center
    p.mt-7.px-8.text-xs
      = link_to t('static_pages.tos'), '#', class: 'link text-blue-500'
      = t('information.and')
      = link_to t('static_pages.privacy_policy'), '#', class: 'link text-blue-500'
      = t('information.consent')
    .divider.w-full.px-8.py-3.md:max-w-2xl
  .grid.place-items-center
    p  = t('.have_an_account')
    .mt-3.mb-10
      = link_to t('.to_login_page'), login_path, class: 'btn btn-primary btn-outline btn-wide'